export const SUCCESS_CODES: any = {
  LOGIN_SUCCESS: 'LOGIN SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT SUCCESS',
  CREATE_SUCCESSFULLY: 'CREATE SUCCESSFULLY',
  DELETE_SUCCESSFULLY: 'DELETE SUCCESSFULLY',
  UPDATE_SUCCESSFULLY: 'UPDATE SUCCESSFULLY',
  GET_SUCCESSFULLY: 'GET SUCCESSFULLY',
};
